akm:
  magSize: 30
  magName: akm_mag
  fireCoolDown: 0.1
  reloadTime: 4.0
  slownessLevel: 2
  slownessLevelAim: 4
  hitDamage: 7.0
  range: 300.0
  recoil: 0.0
  fireSwingIntensity: 0.15
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
mk18:
  magSize: 30
  magName: mk18_mag
  fireCoolDown: 0.08
  reloadTime: 3.0
  slownessLevel: 1
  slownessLevelAim: 5
  hitDamage: 5.0
  range: 300.0
  recoil: 0.0
  fireSwingIntensity: 0.1
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
m249:
  magSize: 100
  magName: m249_mag
  fireCoolDown: 0.06
  reloadTime: 8.0
  slownessLevel: 3
  slownessLevelAim: 5
  hitDamage: 2.5
  range: 300.0
  recoil: 0.0
  fireSwingIntensity: 0.08
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
taurus:
  magSize: 17
  magName: taurus_mag
  fireCoolDown: 0.2
  reloadTime: 2.0
  slownessLevel: 1
  slownessLevelAim: 2
  hitDamage: 4.0
  range: 150.0
  recoil: 0.0
  fireSwingIntensity: 0.05
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
m3:
  magSize: 8
  magName: m3_ammo
  fireCoolDown: 1.25
  reloadTime: 4.0
  slownessLevel: 2
  slownessLevelAim: 3
  hitDamage: 3.0
  range: 75.0
  recoil: 0.0
  fireSwingIntensity: 0.3
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
mp5:
  magSize: 25
  magName: mp5_mag
  fireCoolDown: 0.075
  reloadTime: 3.0
  slownessLevel: 1
  slownessLevelAim: 3
  hitDamage: 5.0
  range: 200.0
  recoil: 0.0
  fireSwingIntensity: 0.05
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
p90:
  magSize: 50
  magName: p90_mag
  fireCoolDown: 0.06
  reloadTime: 3.0
  slownessLevel: 1
  slownessLevelAim: 3
  hitDamage: 5.0
  range: 200.0
  recoil: 0.0
  fireSwingIntensity: 0.065
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
awp:
  magSize: 10
  magName: awp_mag
  fireCoolDown: 1.0
  reloadTime: 5.0
  slownessLevel: 3
  slownessLevelAim: 10
  hitDamage: 30.0
  range: 600.0
  recoil: 0.0
  fireSwingIntensity: 0.25
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
barrett:
  magSize: 10
  magName: barrett_mag
  fireCoolDown: 1.0
  reloadTime: 5.0
  slownessLevel: 3
  slownessLevelAim: 10
  hitDamage: 15.0
  range: 1850.0
  recoil: 0.0
  fireSwingIntensity: 0.2
  fireSwingDuration: 0.1
  particle: minecraft:basic_crit_particle
